# Generated by Django 5.0.2 on 2024-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ach_from', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1500)),
                ('image', models.ImageField(upload_to='static/images/achievements')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/images/experiences')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
                ('link_address', models.URLField()),
                ('link_icon', models.ImageField(upload_to='static/images/links/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=50)),
                ('short_description', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=2000)),
                ('icon', models.ImageField(upload_to='static/images/projects')),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_type', models.CharField(max_length=200)),
                ('skill_description', models.TextField(max_length=1000)),
                ('skill_icon', models.ImageField(upload_to='static/images/skills')),
            ],
        ),
    ]
