# Generated by Django 5.0.2 on 2024-02-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peash', '0002_about_type_alter_project_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='canv_img',
            field=models.ImageField(upload_to='images/peash'),
        ),
        migrations.AlterField(
            model_name='about',
            name='pro_img',
            field=models.ImageField(upload_to='images/peash'),
        ),
        migrations.AlterField(
            model_name='achivement',
            name='image',
            field=models.ImageField(upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(upload_to='experiences/'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_icon',
            field=models.ImageField(upload_to='links/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_icon',
            field=models.ImageField(upload_to='skills/'),
        ),
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(upload_to='skills'),
        ),
    ]
