# Generated by Django 5.0.2 on 2024-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peash', '0003_alter_about_canv_img_alter_about_pro_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='canv_img',
            field=models.ImageField(upload_to='peash/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='pro_img',
            field=models.ImageField(upload_to='peash/'),
        ),
        migrations.AlterField(
            model_name='type',
            name='icon',
            field=models.ImageField(upload_to='types/'),
        ),
    ]
