# Generated by Django 5.0.2 on 2024-02-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peash', '0004_alter_about_canv_img_alter_about_pro_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
