# Generated by Django 5.0.2 on 2024-02-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peash', '0005_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
