# Generated by Django 5.0.2 on 2024-02-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peash', '0007_education_extracurricular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracurricular',
            old_name='edu_from',
            new_name='org',
        ),
        migrations.RenameField(
            model_name='extracurricular',
            old_name='name',
            new_name='post',
        ),
    ]
