# Generated by Django 5.0.2 on 2024-02-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peash', '0008_rename_edu_from_extracurricular_org_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracurricular',
            old_name='org',
            new_name='org_name',
        ),
        migrations.RenameField(
            model_name='extracurricular',
            old_name='post',
            new_name='post_name',
        ),
    ]
