# Generated by Django 5.0.2 on 2024-02-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peash', '0009_rename_org_extracurricular_org_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='peash/')),
            ],
        ),
    ]
