# Generated by Django 4.2.7 on 2024-03-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peash', '0010_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoDest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(null=True, upload_to='links/')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(default='projects/default.png', upload_to='projects/'),
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_project', to='peash.project')),
                ('repo_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_dest_repo', to='peash.repodest')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='projects/')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_project', to='peash.project')),
            ],
        ),
    ]
