from django.contrib import admin
from.models import *
admin.site.register(Link)
admin.site.register(Skill)
admin.site.register(Achivement)
admin.site.register(Experience)
admin.site.register(Project)
admin.site.register(About)
admin.site.register(Type)
admin.site.register(Education)
admin.site.register(Extracurricular)
admin.site.register(Resume)
admin.site.register(RepoDest)
admin.site.register(Repo)
admin.site.register(ExtraImage)
admin.site.register(Tool)
